use url hash to select tab
gobitfly/beaconchain pull request #468
Opened 2024-06-13 07:41 UTC by MauserBitfly

This PR:
- introduces a new composable to select tabs based on the url hash
- adds this composable to the dashboard page

Note to the tester: url hashes are not sent to the server and therefor not available during SSR

2024-06-13 08:41 UTC, D13ce requested changes
Nice and future proof implementation, well done. Just spotted 2 warnings, see my comment below :point_down:

2024-06-13 08:41 UTC, D13ce commented on frontend/composables/useHashTabs.ts
**Bug:** I am on a private dashboard and click the rewards tab to get the `#rewards'' in the URL. I then head-reload (`CTRL`+`F5`) and get the following two warnings:
![image](https://github.com/gobitfly/beaconchain/assets/114066135/b0a47a15-16b8-4e07-af25-4fccafc60b8e)
```
[nuxt] Calling `useRoute` within middleware may lead to misleading results. Instead, use the (to, from) arguments passed to the middleware to access the new and old routes. 6 [composables:12:13](https://local.beaconcha.in:3000/_nuxt/node_modules/nuxt/dist/app/composables/)
[Vue Router warn]: Couldn't find element using selector "#rewards" returned by scrollBehavior. 2 [vue-router.mjs:35:17](https://local.beaconcha.in:3000/_nuxt/node_modules/vue-router/dist/vue-router.mjs)
```

2024-06-13 11:13 UTC, MauserBitfly commented on frontend/composables/useHashTabs.ts
fixed these two warnings

2024-06-13 12:06 UTC, D13ce commented on frontend/composables/useHashTabs.ts
Switching tabs now causes the page to scroll to the top.
Furthermore, reloading while being on `#rewards'' causes the page to switch to `#summary`.

2024-06-13 13:03 UTC, MauserBitfly commented on frontend/composables/useHashTabs.ts
oh sorry, should work again

2024-06-14 08:42 UTC, D13ce approved these changes
LGTM

2024-06-14 08:45 UTC, merged