summary chart v2.5
gobitfly/beaconchain pull request #539
Opened 2024-07-02 06:22 UTC by LuccaBitfly

2024-07-03 11:21 UTC, MauserBitfly approved these changes
LGTM

2024-07-04 10:54 UTC, remoterami requested changes
some minor issues, ptal

2024-07-04 10:54 UTC, remoterami commented on backend/pkg/api/data_access/user.go
> +				ProductIdYearly:          "vdb_addon_1k.year	ly",
typo
```suggestion
				ProductIdYearly:          "vdb_addon_1k.yearly",
```

2024-07-05 10:02 UTC, remoterami commented
lgtm

2024-07-05 10:03 UTC, remoterami approved these changes

2024-07-05 10:03 UTC, merged