Bids 2858/notifications management dashboard table
gobitfly/beaconchain pull request #558
Opened 2024-07-05 07:06 UTC by MauserBitfly

This PR:
- creates the notifications management dashboard table
- adds the table to the management modal
- moves the management modal file/translations

This PR does not:
- use the 'real' API / types (as they don't exist yes)
- create and open edit dialogs 
- implement the delete / reset function

2024-07-05 09:36 UTC, D13ce requested changes
Good step, a few adaptions will be required though, see below :point_down:

2024-07-05 09:36 UTC, D13ce commented on frontend/stores/notifications/useNotificationsManagementDashboardStore.ts
**Question:** As discussed, I am not sure whether this should be a store, a composable or something else.
Notifications are always private so accessing and rendering the data on the server does not provide any real benefits, right?

Just as a note: Keep in mind that we will have several tabs in this modal, all of them storing data and all of them having their own endpoints to `GET`/`PUT` the data. Maybe this should be considered, maybe it does not matter now.

2024-07-05 09:36 UTC, D13ce commented on frontend/components/notifications/management/NotificationsManagementDashboards.vue
> +        </Column>
**Bug:** Compared to the **Design**,
![image](https://github.com/gobitfly/beaconchain/assets/114066135/aa6411c1-4831-46dd-93fc-00a453241738)
the **Implementation** is missing the dashboard type icon
![image](https://github.com/gobitfly/beaconchain/assets/114066135/51993d77-8aa1-4263-a776-71913423db8f)

2024-07-05 09:36 UTC, D13ce commented on frontend/components/notifications/management/NotificationsManagementDashboards.vue
> +  }*/
**Nitpick:** Please remove.

2024-07-05 09:43 UTC, MauserBitfly commented on frontend/public/mock/notifications/managementDashboard.json
> +      "subscriptions": ["missed_attestation", "proposed_attestation"],
will be adapted once we get the API definitions (so resolve for now)

2024-07-08 10:14 UTC, D13ce commented on frontend/stores/notifications/useNotificationsManagementDashboardStore.ts
Jeah, I like that. Thanks!

2024-07-08 10:29 UTC, D13ce approved these changes
LGTM

2024-07-08 10:38 UTC, merged