BIDS-2848: Implement NotificationsDashboardsTable
gobitfly/beaconchain pull request #562
Opened 2024-07-08 07:52 UTC by marcel-bitfly

- mock Network Switcher
- mock table data
- mock entity popout
- implement table

See: BIDS-2848

2024-07-09 07:36 UTC, D13ce commented on frontend/public/mock/notifications/dashboards.json
> +      "dashboardName": "This is a very long name",
+1 for this test.

2024-07-09 09:15 UTC, D13ce requested changes
Impressive work after so little time, well done! :rocket: 

Some more work will be needed though, see my comments below :point_down:

2024-07-09 09:23 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTable.vue
> +            <!-- TODO: implement number of subscriptions -->
@MauserBitfly told me we might get that at a later point, and should first discuss things with our `backend people`

Could this info be implemented already?

2024-07-09 09:43 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTableEmpty.vue
> +.empty {
nice catch thx

2024-07-09 10:22 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTable.vue
> +            class="rewards-table"
copycat me :cat2:

2024-07-09 11:58 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTable.vue
> +                  </div>
refactored it...I hope it is easier to comprehend now

2024-07-09 12:00 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTable.vue
> +  padding-inline: 0px !important
Ideally this should be done by https://nuxt.com/modules/stylelint

2024-07-09 12:02 UTC, marcel-bitfly commented on frontend/pages/notifications.vue
> +          <NotificationsDashboardsTable @open-dialog="openManageNotifications" />
this should makes sure the same `implementation` and `action` is triggerd as if the button is clicked?

Was that even your question?

2024-07-10 06:09 UTC, marcel-bitfly commented on frontend/components/notifications/DashboardsTable.vue
> +            data-key="dashboardId"
yeah after consultation with our `backend people` about the `data format` I'll know what to put here

See: https://github.com/gobitfly/beaconchain/pull/562/files#diff-ad1035c6507cc771bb85899fb2eece87db9676a2cee2d426c1a55339a5407586R79

2024-07-10 06:57 UTC, MauserBitfly commented on frontend/components/notifications/DashboardsTable.vue
> +            <!-- TODO: implement number of subscriptions -->
@D13ce : because that data will come from the notifications overview data which is being implemented in a different PR.

2024-07-10 06:58 UTC, D13ce commented on frontend/components/notifications/DashboardsTable.vue
No need to be sorry, thanks for clearing things up :rocket:

2024-07-10 07:13 UTC, D13ce commented on frontend/pages/notifications.vue
> +          <NotificationsDashboardsTable @open-dialog="openManageNotifications" />
Ah, sorry, I have misread your code. Resolved.

2024-07-10 07:14 UTC, D13ce approved these changes
LGTM :rocket:

2024-07-10 07:23 UTC, merged