Adapt 'validator status' presentation
gobitfly/beaconchain pull request #587
Opened 2024-07-16 07:38 UTC by marcel-bitfly

New 'types` were added, some where renamend.
When including 'online` they should appear green.
When including 'offline` they should appear red.
Otherwise orange.

See: BIDS-3218

2024-07-16 07:44 UTC, marcel-bitfly commented
is this an issue?
![image](https://github.com/user-attachments/assets/6d1c9522-0fc2-4635-917a-a608ea2a6f59)

2024-07-16 12:06 UTC, D13ce requested changes

2024-07-16 13:38 UTC, marcel-bitfly commented on frontend/components/validator/table/ValidatorTableStatus.vue
@LuccaBitfly could the problem be on the `backend`?

2024-07-17 08:54 UTC, LuccaBitfly commented on frontend/components/validator/table/ValidatorTableStatus.vue
@marcel-bitfly Yes the new states still need to be handled correctly in data access.

2024-07-18 10:20 UTC, D13ce approved these changes
As discussed, frontend changes seem to be fine.

2024-07-18 10:20 UTC, merged