Mobile App Authentication
gobitfly/beaconchain pull request #602
Opened 2024-07-22 10:12 UTC by manuelsc

wip do not merge

2024-07-30 11:15 UTC, LuccaBitfly requested changes

2024-07-30 11:15 UTC, LuccaBitfly commented on backend/pkg/api/router.go
> +		{http.MethodPost, "/mobile/notify/register", nil, hs.InternalRegisterMobilePushToken},
If we want this endpoint to fit with the other notification endpoints, we could have it be:
```
PUT /api/i/users/me/notifications/settings/paired-devices/{client_id}/token
```

2024-07-30 11:15 UTC, LuccaBitfly commented on backend/pkg/api/handlers/backward_compat.go
maybe just rename to `mobile.go` and also move other mobile-related funcs here.

2024-07-30 11:15 UTC, LuccaBitfly commented on backend/pkg/commons/utils/user.go
> +		if !isWellKnownDomain && len(domainParts[0]) > 2 {
This can be done with the std lib
```suggestion
		if !slices.Contains(wellKnownDomains, domainParts[0]) && len(domainParts[0]) > 2 {
```

2024-07-30 11:15 UTC, LuccaBitfly commented on backend/pkg/api/handlers/auth.go
> +
Missing:
```go
if v.hasErrors() {
	handleErr(w, v)
	return
}
```

2024-07-30 11:18 UTC, LuccaBitfly commented
Couldn't test with whether this works with the mobile app obviously, so I trust that you've done this. For FE or data access stuff you should prob get someone from the respective team to review the code.

2024-07-30 11:44 UTC, manuelsc commented on frontend/pages/login.vue
already reviewed by mauser

2024-07-30 11:51 UTC, manuelsc commented on backend/pkg/api/handlers/backward_compat.go
I'd like to leave it with the backwards compat name to indicate that this is a developer debt that can be removed at some point in the future.

2024-08-07 06:05 UTC, LuccaBitfly approved these changes
lgtm

2024-08-07 06:34 UTC, merged