(BIDS-3288) API: added total ETH staked to VDB overview
gobitfly/beaconchain pull request #667
Opened 2024-08-05 09:25 UTC by remoterami

2024-08-08 08:00 UTC, manuelsc approved these changes
utACK

2024-08-12 10:24 UTC, MauserBitfly approved these changes
LGTM from FE point of view

2024-08-14 06:39 UTC, LuccaBitfly requested changes
lgtm

2024-08-14 06:39 UTC, LuccaBitfly approved these changes
lgtm

2024-08-14 08:27 UTC, merged