Beds 157/add balance to overview
gobitfly/beaconchain pull request #771
Opened 2024-08-23 13:07 UTC by Eisei24

2024-08-23 13:16 UTC, Eisei24 commented on backend/pkg/api/data_access/vdb_management.go
> -		var query string
No need to get the validator status from the db if we have it in the cache.

2024-08-23 13:25 UTC, Eisei24 commented on backend/pkg/api/data_access/vdb_management.go
> +			totalNonRpDeposits, err := d.GetValidatorDashboardTotalClDeposits(ctx, nonRpDashboardId)
I assumed `StakedEth` means CL deposits for non-rocketpool validators.
If that is not the case please comment here.

2024-08-28 11:25 UTC, remoterami requested changes
I'd do some small changes, ptal

2024-08-28 12:30 UTC, invis-bitfly approved these changes

2024-08-28 12:32 UTC, guybrush approved these changes

2024-08-28 12:33 UTC, remoterami approved these changes

2024-08-28 12:33 UTC, merged